apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    kiamol: ch11
spec:
  ports:
    - port: 8080
      targetPort: jenkins
  selector:
    app: jenkins
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  jenkins
  labels:
    kiamol: ch11
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: kiamol/ch11-jenkins
          ports:
            - name: jenkins
              containerPort: 8080
          volumeMounts:
            - name: registry-creds
              mountPath: /root/.docker
              readOnly: true
      volumes:
        - name: registry-creds
          secret:
            secretName: registry-creds2
            defaultMode: 0400
            items:
            - key: .dockerconfigjson
              path: config.json
