apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: hello-kiamol
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: hello-kiamol
          servicePort: 80