apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
    kiamol: ch11
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: jenkins
          image: kiamol/ch11-jenkins
          env:
          - name: REGISTRY_SERVER
            value: {{ .Values.registryServer }}
          ports:
            - name: jenkins
              containerPort: 8080
          volumeMounts:
            - name: registry-creds
              mountPath: /root/.docker
              readOnly: true
      volumes:
        - name: registry-creds
          secret:
            secretName: {{ .Values.registrySecretName }}
            defaultMode: 0400
            items:
            - key: .dockerconfigjson
              path: config.json
