apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
    kiamol: ch11
spec:
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: jenkins
  selector:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.serviceType }}