apiVersion: v1
kind: Service
metadata:
  name: numbers-api
  labels:
    app: numbers-api
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: numbers-api
  type: ClusterIP