apiVersion: v1
kind: Service
metadata:
  name: numbers-web
  labels:
    app: numbers-web
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: numbers-web
  type: LoadBalancer