apiVersion: v1
kind: Service
metadata:
  name: numbers-web
  labels:
    kiamol: ch18
spec:
  ports:
    - port: 8090
      targetPort: 80
  selector:
    app: numbers
    component: web
  type: LoadBalancer