apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-tools
  labels:
    kiamol: ch19
spec:
  selector:
    matchLabels:
      app: rbac-tools
  template:
    metadata:
      labels:
        app: rbac-tools
    spec:
      serviceAccountName: rbac-tools
      containers:
      - name: rbac-tools
        image: kiamol/ch19-rbac-tools